services:
  web:
    container_name: ${CONTAINER}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT:-production}
        NGINX_FROM_IMAGE: nginx:mainline-alpine-slim
        ENABLED_MODULES: brotli

    labels:
      - traefik.enable=true

      - traefik.http.routers.${CONTAINER}-http.rule=Host(`${HOST}`)
      - traefik.http.routers.${CONTAINER}-http.entrypoints=web
      - traefik.http.routers.${CONTAINER}-http.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

      - traefik.http.routers.${CONTAINER}.rule=Host(`${HOST}`)
      - traefik.http.routers.${CONTAINER}.entrypoints=websecure
      - traefik.http.routers.${CONTAINER}.tls.certresolver=le
      - traefik.http.services.${CONTAINER}.loadbalancer.server.port=80
      - traefik.docker.network=proxy

    environment:
      - NODE_ENV=${ENVIRONMENT:-production}

    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
