worker_processes 2;
load_module modules/ngx_http_brotli_static_module.so;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    keepalive_timeout  60;

    server {
        listen        80;
        server_name   strnadi.cz;
        brotli_static on;
        root /usr/share/nginx/html;

        # Disable caching for service worker and manifest
        location ~* (sw\.js|manifest\.webmanifest)$ {
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            expires off;
            access_log off;
            try_files $uri =404;
        }

        # Disable caching for HTML files
        location ~* \.html$ {
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            expires off;
            try_files $uri /index.html;
        }

        # Cache hashed assets for a long time
        location ~* \.(?:css|js)$ {
            if ($uri ~* "\.[a-f0-9]{8,}\.") {
                add_header Cache-Control "public, max-age=31536000, immutable";
            }
            try_files $uri /index.html;
        }

        location / {
            try_files $uri /index.html;
        }

        location = /.well-known/apple-app-site-association {
            default_type application/json;
            add_header Content-Type application/json;
            try_files    $uri =404;
        }
    }
}
