worker_processes 2;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    brotli_static on;
    sendfile      on;

    keepalive_timeout  60;

    server {
        listen       80;
        server_name  strnadi.cz;

        location / {
            root /usr/share/nginx/html;
            try_files $uri /index.html;
        }
    }
}
